RCL_Inventory/Controllers/AboutUsController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Identity;
using RCL_Inventory.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.Extensions.Logging;


namespace RCL_Inventory.Controllers
{
    public class AboutUsController : Controller
    {
        private readonly ILogger<AboutUsController> _logger;


        public AboutUsController(ILogger<AboutUsController> logger)
        {
            _logger = logger;
        }


        // Method Get to show the About Us View.
        public IActionResult Index()
        {
            return View();
        }
    }
}

RCL_Inventory/Controllers/AddressesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using RCL_Inventory.Models;

namespace RCL_Inventory.Controllers
{
    [Authorize(Roles = "Admin")]
    public class AddressesController : Controller
    {
        private readonly InventoryContext _context;

        public AddressesController(InventoryContext context)
        {
            _context = context;
        }

        // Method Get to show Address Information.
        public async Task<IActionResult> Index()
        {
            return View(await _context.Addresses.ToListAsync());
        }


        // Method Get of Details Address.
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var address = await _context.Addresses
                .FirstOrDefaultAsync(m => m.AddressId == id);
            if (address == null)
            {
                return NotFound();
            }

            return View(address);
        }


        // Method Get of Create a new Address.
        public IActionResult Create()
        {
            return View();
        }

        // Method Post of Create a new Address.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("AddressId,Country,City,Province,PostalCode,Street")] Address address)
        {
            if (ModelState.IsValid)
            {
                _context.Add(address);
                await _context.SaveChangesAsync();
                TempData["success"] = "Information Added successfully.";
                return RedirectToAction(nameof(Index));
            }
            TempData["failed"] = "Failed. Please, select and fill all the fields.";
            return View(address);
        }

        // Method Get of Edit Address.
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var address = await _context.Addresses.FindAsync(id);
            if (address == null)
            {
                return NotFound();
            }
            return View(address);
        }

        // Method Post of Edit Address.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("AddressId,Country,City,Province,PostalCode,Street")] Address address)
        {
            if (id != address.AddressId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(address);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AddressExists(address.AddressId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                TempData["success"] = "Information edited successfully.";
                return RedirectToAction(nameof(Index));
            }
            TempData["failed"] = "Failed. Please, fill all the fields.";
            return View(address);
        }

        // Method Get of Delete Address.
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var address = await _context.Addresses
                .FirstOrDefaultAsync(m => m.AddressId == id);
            if (address == null)
            {
                return NotFound();
            }

            return View(address);
        }

        // Method Post of Delete Address.
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var address = await _context.Addresses.FindAsync(id);
            _context.Addresses.Remove(address);
            await _context.SaveChangesAsync();
            TempData["success"] = "Information deleted successfully.";
            return RedirectToAction(nameof(Index));
        }

        private bool AddressExists(int id)
        {
            return _context.Addresses.Any(e => e.AddressId == id);
        }
    }
}

RCL_Inventory/Controllers/HelpController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Identity;
using RCL_Inventory.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.Extensions.Logging;


namespace RCL_Inventory.Controllers
{
    public class HelpController : Controller
    {
        private readonly ILogger<HelpController> _logger;


        public HelpController(ILogger<HelpController> logger)
        {
            _logger = logger;
        }

        // Method Get to show the Home View.
        public IActionResult Index()
        {
            return View();
        }
    }
}

RCL_Inventory/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using RCL_Inventory.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace RCL_Inventory.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        // Method Get to show the Home View.
        public IActionResult Index()
        {
            return View();
        }

    }
}

RCL_Inventory/Controllers/ProductsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using RCL_Inventory.Models;
using RCL_Inventory.Models.ViewModels.ViewModelProduct;
using Microsoft.AspNetCore.Authorization;

namespace RCL_Inventory.Controllers
{
    [Authorize]
    public class ProductsController : Controller
    {
        private readonly InventoryContext _context;

        public ProductsController(InventoryContext context)
        {
            _context = context;
        }

        // Method Get of Products Information.
        public IActionResult Index()
        {
            var inventoryContext = _context.Products.Include(p => p.Category);
            return View(inventoryContext.ToList());
        }

        // Method Get of Products Details.
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var product = await _context.Products
                .Include(p => p.Category)
                .FirstOrDefaultAsync(m => m.ProductId == id);
            if (product == null)
            {
                return NotFound();
            }

            return View(product);
        }

        // Method Get of Create a new Product.
        public IActionResult Create()
        {
            var categories = _context.Categories.ToList();

             ProductViewModel ppvw = new ProductViewModel()
            {
                CategoriesList = categories
            };
            return View(ppvw);
        }

        // Method Post of Create a new Product.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ProductId,Name,Description,Brand,CategoryId")] Product product)
        {

            if (ModelState.IsValid)
            {
                _context.Add(product);
                await _context.SaveChangesAsync();
                TempData["success"] = "Information Added successfully.";
                return RedirectToAction(nameof(Index));
            }

            var categories = _context.Categories.ToList();

            ProductViewModel ppvw = new ProductViewModel()
            {
                CategoriesList = categories
            };

            TempData["failed"] = "Failed. Please, select and fill all the fields.";
            ViewData["CategoryId"] = new SelectList(_context.Categories, "CategoryId", "Name", product.CategoryId);
            return View(ppvw);
        }

        // Method Get of Edit a Product.
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var product = await _context.Products.FindAsync(id);

            int productId = product.ProductId;
            ProductViewModel pvm = new ProductViewModel()
            {
                CategoriesList = _context.Categories.ToList(),
                ProductId = productId
            };


            if (product == null)
            {
                return NotFound();
            }
            ViewData["CategoryId"] = new SelectList(_context.Categories, "CategoryId", "Name", product.CategoryId);

            return View(pvm);
        }

        // Method Post of Edit a Product.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ProductId,Name,Description,Brand,CategoryId")] Product product)
        {

            if (ModelState.IsValid)
            {

                Product productClass = new Product()
                {
                    ProductId = id,
                    CategoryId = product.CategoryId,
                    Name = product.Name,
                    Brand = product.Brand,
                    Description = product.Description
                };


                try
                {
                    _context.Update(productClass);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProductExists(product.ProductId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                TempData["success"] = "Information edited successfully.";
                return RedirectToAction(nameof(Index));
            }

            ProductViewModel pvm = new ProductViewModel()
            {
                CategoriesList = _context.Categories.ToList(),
                ProductId = id
            };
            TempData["failed"] = "Failed. Please, select and fill all the fields.";
            ViewData["CategoryId"] = new SelectList(_context.Categories, "CategoryId", "Name", product.CategoryId);
            return View(pvm);
        }

        // Method Get of Delete a Product.
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var product = await _context.Products
                .Include(p => p.Category)
                .FirstOrDefaultAsync(m => m.ProductId == id);
            if (product == null)
            {
                return NotFound();
            }

            return View(product);
        }

        // Method Post of Delete a Product.
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var product = await _context.Products.FindAsync(id);
            _context.Products.Remove(product);
            await _context.SaveChangesAsync();
            TempData["success"] = "Information deleted successfully.";
            return RedirectToAction(nameof(Index));
        }

        private bool ProductExists(int id)
        {
            return _context.Products.Any(e => e.ProductId == id);
        }
    }
}

RCL_Inventory/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}


<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
<link rel="stylesheet" href="//cdn.datatables.net/1.11.5/css/jquery.dataTables.min.css" />
<link rel="stylesheet" href="~/css/sitee.css" />
<link rel="stylesheet" href="~/css/home.css" />
<script src='https://kit.fontawesome.com/a076d05399.js' crossorigin='anonymous'></script>



<hr />
<br />
<hr class="midleLine" />
<br />
<hr />
<p>

</p>

<div class="cardBox">

    @if (signInManager.IsSignedIn(User))
    {
        <div class="card" onclick="location.href='@Url.Action("", "Categories")'">
            <div>

                <div class="contentBox"></div>
                <div class="iconBx">

                    <icon-icon name="category"><a asp-area="" asp-controller="Categories" asp-action="Index"><i class='fas fa-tags'></i></a>

                </div>
                <ul>
                    <li style="list-style-type:none"><a asp-area="" asp-controller="Categories" asp-action="Index">Categories</a></li>
                    <li style="list-style-type:none"><a asp-area="" asp-controller="Categories" asp-action="Create">New Product Category</a></li>
                </ul>
            </div>

        </div>
    }

    @if (signInManager.IsSignedIn(User))
    {
        <div class="card" onclick="location.href='@Url.Action("", "Products")'">
            <div>
                <div class="contentBox"></div>
                <div class="iconBx">
                    <icon-icon name="category"><a asp-area="" asp-controller="Products" asp-action="Index"><i class='fas fa-cubes'></i></a>
                </div>
                <ul>
                    <li style="list-style-type:none"><a asp-area="" asp-controller="Products" asp-action="Index">Products</a></li>
                    <li style="list-style-type:none"><a asp-area="" asp-controller="Products" asp-action="Create">Create a new Product</a></li>
                </ul>
            </div>
        </div>
    }



    @if (signInManager.IsSignedIn(User))
    {
<div class="card" onclick="location.href='@Url.Action("", "Transactions")'">
 
            <div class="iconBx">
                <icon-icon name="category"><a asp-area="" asp-controller="Transactions" asp-action="Index"><i class='fas fa-exchange-alt'></i></a>
            </div>
            <div class="contentBox" style="text-align:center"><a asp-area="" asp-controller="Transactions" asp-action="Index">Transactions</a></div>

        </div>

    


    }

    @inject SignInManager<User> signInManager
    @if (signInManager.IsSignedIn(User) && User.IsInRole("Admin"))
    {
        <div class="card" onclick="location.href='@Url.Action("", "Addresses")'" >
            <div>
                <div class="contentBox"></div>
                <div class="iconBx">
                    <icon-icon name="category"><a asp-area="" asp-controller="Addresses" asp-action="Index"><i class='far fa-id-card'></i></a>
                </div>
                <ul>
                    <li style="list-style-type:none"><a asp-area="" asp-controller="Addresses" asp-action="Index">Addresses</a></li>
                    <li style="list-style-type:none"><a asp-area="" asp-controller="Addresses" asp-action="Create">Create a new Address</a></li>
                </ul>
            </div>
        </div>

    }

    @if (signInManager.IsSignedIn(User) && User.IsInRole("Admin"))
    {
        <div class="card" onclick="location.href='@Url.Action("", "Suppliers")'">
            <div>
                <div class="contentBox"></div>
                <div class="iconBx">
                    <icon-icon name="category"><a asp-area="" asp-controller="Supplieres" asp-action="Index"><i class='fas fa-handshake'></i></a>
                </div>
                <ul>
                    <li style="list-style-type:none"><a asp-area="" asp-controller="Suppliers" asp-action="Index">Suppliers</a></li>
                    <li style="list-style-type:none"><a asp-area="" asp-controller="Suppliers" asp-action="Create">Create a new Supplier</a></li>
                </ul>
            </div>
        </div>
    }

    <div class="card" onclick="location.href='@Url.Action("", "AboutUs")'" >
        <div class="iconBx">
            <icon-icon name="category"><a asp-area="" asp-controller="AboutUs" asp-action="Index"><i class='fas fa-users'></i></a>
        </div>
        <div>
            <div class="contentBox" style="text-align:center">About Us</div>
        </div>

    </div>

    <div class="card" onclick="location.href='@Url.Action("", "Help")'" >
            <div>
                <div class="iconBx">
                    <icon-icon name="category"><a asp-area="" asp-controller="Help" asp-action="Index"><i class='far fa-question-circle'></i></a>
                </div>
                <div class="contentBox" style="text-align:center">Help</div>

            </div>
    </div>


    <div class="card"  onclick="location.href='@Url.Action("", "ContactUs")'" >
        <div>
            <div class="iconBx">
               
                <icon-icon name="category"><a asp-area="" asp-controller="ContactUs" asp-action="Index"><i class='fas fa-headset'></i></a>
            </div>
            <div class="contentBox" style="text-align:center">Contact Us</div>
        </div>
    </div>


    <script type="module" src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js"></script>
    <script nomodule src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.js"></script>
</div>

<hr class="midleLine" />






@section Scripts {

    <script>
        $(document).ready(function () {
            $('#myTable').DataTable();
        });
    </script>
}