RCL_Inventory/Models/DBGenerator/TransactionType.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel;

namespace RCL_Inventory.Models
{
    public class TransactionType
    {
       [Key]
        [DisplayName("Transaction Type ID")]
        public int TransactionTypeId { get; set; }
        [Required(ErrorMessage = "Please, need to write Country Name.")]
        [DisplayName("Transaction Type")]
        public string Name { get; set; }

    }
}

RCL_Inventory/Controllers/TransactionsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using RCL_Inventory.Models;
using RCL_Inventory.Models.ViewModels;
using Microsoft.AspNetCore.Authorization;

namespace RCL_Inventory.Controllers
{
    [Authorize]
    public class TransactionsController : Controller
    {
        private readonly InventoryContext _context;

        public TransactionsController(InventoryContext context)
        {
            _context = context;
        }



        // Method Get to show Transaction Information.
        [HttpGet]
        public async Task<IActionResult> Index()
        {


            var transaction = await _context.Transaction
                .Include(t => t.Product)
                 .Include(t => t.Product.Category)
                .Include(t => t.Supplier)
                .Include(t => t.TransactionType).ToListAsync();

            var products = _context.Products.Include(t => t.Category).ToList(); ;
            var suppliers = _context.Suppliers.Include(t => t.Address).ToList();
            var categories = _context.Categories.ToList();
            var transactions = _context.Transaction.Include(t=>t.TransactionType).ToList();

            PurchaseProductViewModels ppvw = new PurchaseProductViewModels()
            {
                ProductsList = products,
                SuppliersList = suppliers,
                CategoriesList = categories,
                TransactionsList = transaction,
                
            };



            ViewData["TransactionTypeId"] = new SelectList(_context.TransactionTypes, "TransactionTypeId", "Name");

            return View(ppvw);
        }

        // Method Post to filter and show Transaction Information accourding with the Transaction Type.
        [HttpPost]
        public async Task<IActionResult> Index(int? id)
        { 

            var transaction = _context.Transaction
          .Include(t => t.Product)
           .Include(t => t.Product.Category)
          .Include(t => t.Supplier)
          .Include(t => t.TransactionType).Where(t => t.TransactionTypeId == id.Value).ToList();

            List<Transaction> transactionFilter = new List<Transaction>();
     

            var products = await _context.Products.Include(t => t.Category).ToListAsync();
            var suppliers = await _context.Suppliers.Include(t => t.Address).ToListAsync();
            var categories = await _context.Categories.ToListAsync();

           PurchaseProductViewModels ppvw = new PurchaseProductViewModels()
            {
                ProductsList = products,
                SuppliersList = suppliers,
                CategoriesList = categories,
                TransactionsList = transaction,
                TransactionTypeId = id.Value
            };


            ViewData["TransactionTypeId"] = new SelectList(_context.TransactionTypes, "TransactionTypeId", "Name");

            return View("Index",ppvw);
        }


        // Method Get of Details Transaction
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var transaction = await _context.Transaction
                .Include(t => t.Product)
                 .Include(t => t.Product.Category)
                .Include(t=>t.Supplier)
                .Include(t => t.TransactionType)
                .FirstOrDefaultAsync(m => m.TransactionId == id);
            if (transaction == null)
            {
                return NotFound();
            }

            return View(transaction);
        }


        // Method Get of Create a new Transaction
        [HttpGet]
        public IActionResult CreatePurchase(int? id)
        {
            var products = _context.Products.Include(t => t.Category).ToList(); ;
            var suppliers = _context.Suppliers.Include(t => t.Address).ToList();
            var categories = _context.Categories.ToList();



            PurchaseProductViewModels ppvw = new PurchaseProductViewModels()
            {
                ProductsList = products,
                SuppliersList = suppliers,
                CategoriesList = categories,
                TransactionTypeId = id.Value

            };
            return View(ppvw);
        }


        // Method Post of Create a new Transaction
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreatePurchase(int id,[Bind("TransactionId,Date,ProductId,Quantity,TransactionTypeId,SupplierId")] Transaction transaction)
        {

            




            if (ModelState.IsValid)
            {
                var productId = transaction.ProductId;

                var productContext = _context.Products.Find(productId);

                int categoryInt = productContext.CategoryId;


                Transaction transactionContext = new Transaction()
                {
                    Date = transaction.Date,
                    ProductId = transaction.ProductId,
                    Quantity = transaction.Quantity,
                    TransactionTypeId = id,
                    SupplierId = transaction.SupplierId,
                    Submitted = false
                };



                _context.Add(transactionContext);
                await _context.SaveChangesAsync();
                TempData["success"] = "Information added successfully.";
                return RedirectToAction(nameof(Index));
            }

            var products = _context.Products.Include(t => t.Category).ToList(); ;
            var suppliers = _context.Suppliers.Include(t => t.Address).ToList();
            var categories = _context.Categories.ToList();



            PurchaseProductViewModels ppvw = new PurchaseProductViewModels()
            {
                ProductsList = products,
                SuppliersList = suppliers,
                CategoriesList = categories,
                TransactionTypeId = id

            };


            ViewData["ProductId"] = new SelectList(_context.Products, "ProductId", "Name", transaction.ProductId);
            ViewData["TransactionTypeId"] = new SelectList(_context.TransactionTypes, "TransactionTypeId", "Name", transaction.TransactionTypeId);
            TempData["failed"] = "Failed. Please, select and fill all the fields.";
            return View(ppvw);
        }


        // Method Get of Edit a Transaction
        public async Task<IActionResult> Edit(int? id)
        {
            var products = await _context.Products.Include(t => t.Category).ToListAsync();
            var suppliers = await _context.Suppliers.Include(t => t.Address).ToListAsync();
            var transaction = await _context.Transaction.FindAsync(id);

            int transactionId = transaction.TransactionId;
            int transactionTypeId = transaction.TransactionTypeId;
            var ppvw = new PurchaseProductViewModels()
            {
                ProductsList = products,
                SuppliersList = suppliers,
                TransactionId = transactionId,
                TransactionTypeId = transactionTypeId

            };
            return View(ppvw);
           
        }

        // Method Post of Edit a Transaction
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("TransactionId,Date,ProductId,Quantity,TransactionTypeId,SupplierId")] Transaction transaction)
        {

            if (ModelState.IsValid)
            {
                try
                {
                    var productId = transaction.ProductId;

                    var productContext = _context.Products.Find(productId);

                    int categoryInt = productContext.CategoryId;

                    Transaction transactionContext = new Transaction()
                    {
                        Date = transaction.Date,
                        ProductId = transaction.ProductId,
                        Quantity = transaction.Quantity,
                        TransactionTypeId = transaction.TransactionTypeId,
                        SupplierId = transaction.SupplierId,
                        TransactionId = id

                    };

                    _context.Update(transactionContext);
                    await _context.SaveChangesAsync();          
                }
                catch (DbUpdateConcurrencyException)
                {

                    var productId = transaction.ProductId;

                    var productContext = _context.Products.Find(productId);

                    int categoryInt = productContext.CategoryId;

                    Transaction transactionContext = new Transaction()
                    {
                        Date = transaction.Date,
                        ProductId = transaction.ProductId,
                        Quantity = transaction.Quantity,
                        TransactionTypeId = transaction.TransactionTypeId,
                        SupplierId = transaction.SupplierId,
                        TransactionId = id

                    };


                    if (!TransactionExists(transactionContext.TransactionId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                TempData["success"] = "Information edited successfully.";
                return RedirectToAction(nameof(Index));
            }

            var products = await _context.Products.Include(t => t.Category).ToListAsync();
            var suppliers = await _context.Suppliers.Include(t => t.Address).ToListAsync();
            var transactionHolder = await _context.Transaction.FindAsync(id);

            int transactionId = transactionHolder.TransactionId;

RCL_Inventory/Views/Transactions/Create.cshtml
@model RCL_Inventory.Models.Transaction

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Transaction</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">

            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Date" class="control-label"></label>
                <input asp-for="Date" class="form-control" />
                <span asp-validation-for="Date" class="text-danger"></span>
            </div>
            @*<div class="form-group">
            <label asp-for="CategoryId" class="control-label"></label>
            <input asp-for="CategoryId" class="form-control" />
            <span asp-validation-for="CategoryId" class="text-danger"></span>
        </div>*@


            <!--<div class="form-group">-->
            @*<input type="submit" value="CategoryRefresh" class="btn btn-primary" />*@
            <!--<button asp-action="CategoryRefresh" class="btn btn-secondary"></button>

    </div>-->
            @*<a asp-action="CategoryRefresh"
        asp-controller="Transactions"
        asp-route-id="@vendor.VendorId">Refresh</a>*@

            <div class="form-group">
                <label asp-for="ProductId" class="control-label"></label>
                <select asp-for="ProductId" class="form-control" asp-items="ViewBag.ProductId"></select>
            </div>
            <div class="form-group">
                <label asp-for="Quantity" class="control-label"></label>
                <input asp-for="Quantity" class="form-control" />
                <span asp-validation-for="Quantity" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="TransactionTypeId" class="control-label"></label>
                <select asp-for="TransactionTypeId" class="form-control" asp-items="ViewBag.TransactionTypeId"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

RCL_Inventory/Views/Transactions/CreatePurchase.cshtml
@model PurchaseProductViewModels
<!--IEnumerable<RCL_Inventory.Models.ViewModels.PurchaseProductViewModels>-->



<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
<link rel="stylesheet" href="//cdn.datatables.net/1.11.5/css/jquery.dataTables.min.css" />
<link rel="stylesheet" href="~/css/sitee.css" />
<link rel="stylesheet" href="~/css/category.css" />
<link rel="stylesheet" href="~/css/product.css" />



@{if (Model.TransactionTypeId == 1)
    {
        ViewData["Title"] = "Create a New Purchase";
        <hr />
        <h2 class="title">Create a New Purchase</h2>
        <hr />

    }
    else if (Model.TransactionTypeId == 2)
    {
        ViewData["Title"] = "Create a New Sale";
        <hr />
        <h2 class="title">Create a New Sale</h2>
        <hr />
    }
    else
    {
        ViewData["Title"] = "Create a New Loss";
        <hr />
        <h2 class="title">Create a New Shrinkage</h2>
        <hr />
    }

}
@{ if (TempData["failed"] != null)
    {
        <div class="d-flex justify-content-center alert alert-danger mt-2">
            @TempData["failed"]
        </div>
    }
}



<form asp-action="CreatePurchase" method="post">
    <div asp-validation-summary="ModelOnly" style="color:#b91010"></div>

    <!-- Invisivel atributes -->
    <div hidden class="form-group">
        <input id="ProductId" asp-for="Transaction.ProductId" class="form-control" />
    </div>
    <div hidden class="form-group">
        <input id="SupplierId" asp-for="Transaction.SupplierId" class="form-control" />
    </div>
    <!--Product Table-->
    <div class="card">
        <div class="card-header">Products List</div>
        <div class="card-body">
            <table id="productTable" class="display" style="width:100%">
                <thead>
                    <tr>
                        <th>
                            @Html.DisplayNameFor(model => model.Category.Name)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Products.Name)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Products.Brand)
                        </th>

                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model.ProductsList)
                    {
                        <tr onclick="passProductId('@item.ProductId')">
                            <td>
                                @Html.DisplayFor(modelItem => item.Category.Name)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Name)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Brand)
                            </td>

                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
    <span asp-validation-for="Transaction.ProductId" class="text-danger d-flex justify-content-center"></span>
    <!--Product Table-->
    <div class="card mt-3">
        <div class="card-header">Suppliers List</div>
        <div class="card-body">
            <table id="supplierTable" class="display" style="width:100%">
                <thead>
                    <tr>
                        <th>
                            @Html.DisplayNameFor(model => model.Supplier.SupplierId)

                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Supplier.Name)
                        </th>

                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model.SuppliersList)
                    {
                        <tr onclick="passSupplierId('@item.SupplierId')">
                            <td>
                                @Html.DisplayFor(modelItem => item.SupplierId)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Name)
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
    <span asp-validation-for="Transaction.SupplierId" class="text-danger d-flex justify-content-center"></span>

    <div class="card mt-3 ">
        <div class="card-header"> Transaction Detail</div>
        <div class="card-body row">
            <div class="form-group col-md">
                <div class="form-group">
                    <label asp-for="Transaction.Date" class="control-label d-flex justify-content-center"></label>
                    <input asp-for="Transaction.Date" class="form-control" />
                    <span asp-validation-for="Transaction.Date" class="text-danger d-flex justify-content-center"></span>
                </div>
            </div>
            <div class="form-group col-md">
                <label asp-for="@Model.Transaction.Quantity" class="control-label d-flex justify-content-center"></label>
                <input asp-for="@Model.Transaction.Quantity" class="form-control" />
                <span asp-validation-for="Transaction.Quantity" class="text-danger d-flex justify-content-center"></span>
            </div>
        </div>
    </div>

    @{if (Model.TransactionTypeId == 1)
        {
            <div class="d-flex justify-content-center mt-2">
                <div>
                    <input type="submit" class="btn btn-primary mr-2" style="font-size:20px" value="Create" />|
                </div>
                <div class="ml-2 d-flex btn btn-secondary justify-content-center">
                    <a asp-action="Index" style="font-size:20px; color:white;"> Back</a>
                </div>
            </div>
        }
        else if (Model.TransactionTypeId == 2)
        {
            <div class="d-flex justify-content-center mt-2">
                <div class="mr-2">
                    <input type="submit" class="btn btn-primary mr-2" style="font-size:20px" value="Create" />|
                </div>
                <div class="ml-2 d-flex btn btn-secondary justify-content-center">
                    <a asp-action="Index" style="font-size:20px; color:white;"> Back</a>
                </div>
            </div>
        }
        else
        {
            <div class="d-flex justify-content-center mt-2">
                <div class="mr-2">
                    <input type="submit" class="btn btn-primary mr-2" style="font-size:20px" value="Create" />|
                </div>
                <div class="ml-2 d-flex btn btn-secondary justify-content-center">
                    <a asp-action="Index" style="font-size:20px; color:white;"> Back</a>
                </div>
            </div>
        }

    }



</form>

@section Scripts {
    <script>
        $(document).ready(function () {
            var productTable = $('#productTable').DataTable();

            $('#productTable tbody').on('click', 'tr', function () {
                if ($(this).hasClass('selected')) {
                    $(this).removeClass('selected');
                }
                else {
                    productTable.$('tr.selected').removeClass('selected');
                    $(this).addClass('selected');
                }
            });
        });

        function passProductId(ProductId) {
            document.getElementById('ProductId').value = ProductId;
            console.log(ProductId);
        }



        $(document).ready(function () {
            var supplierTable = $('#supplierTable').DataTable();

            $('#supplierTable tbody').on('click', 'tr', function () {
                if ($(this).hasClass('selected')) {
                    $(this).removeClass('selected');
                }
                else {
                    supplierTable.$('tr.selected').removeClass('selected');
                    $(this).addClass('selected');
                }
            });
        });


        function passSupplierId(SupplierId) {
            document.getElementById('SupplierId').value = SupplierId;
            console.log(SupplierId);
        }


    </script>
}

RCL_Inventory/Views/Transactions/Delete.cshtml
@model RCL_Inventory.Models.Transaction

@{
    ViewData["Title"] = "Delete";
}
<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
<link rel="stylesheet" href="//cdn.datatables.net/1.11.5/css/jquery.dataTables.min.css" />
<link rel="stylesheet" href="~/css/sitee.css" />
<link rel="stylesheet" href="~/css/category.css" />
<link rel="stylesheet" href="~/css/product.css" />

<hr />
<h2 class="title">Delete Transaction</h2>
<hr />

<h3>Are you sure you want to delete this?</h3>

<div>
    <div class="card mt-3">
        <div class="card-header font-weight-bolder d-flex justify-content-center bg-blue  pr-5 ext-white"> Transaction Type</div>
        <div class="card-body d-flex justify-content-center pl-5">
            <h5 class="col-sm-2">
                @Html.DisplayFor(model => model.TransactionType.Name)
            </h5>
        </div>
    </div>
</div>


<div class="card mt-3">
    <div class="card-header font-weight-bolder  text-white bg-blue d-flex justify-content-center"> Transaction Information</div>
    <div class="card-body">
        <div class="card-body row">
            <div class="form-group col-md">
                <label class="d-flex justify-content-center">
                    @Html.DisplayNameFor(model => model.Date)
                </label>
                <input class="form-control" disabled value="@Html.DisplayFor(model => model.Date)" />
            </div>

            <div class="form-group col-md">
                <label class="d-flex justify-content-center">
                    @Html.DisplayNameFor(model => model.Quantity)
                </label>
                <input class="form-control" disabled value="@Html.DisplayFor(model => model.Quantity)" />
            </div>
        </div>
    </div>
</div>

<div class="card mt-3">
    <div class="card-header font-weight-bolder text-white bg-blue  d-flex justify-content-center"> Product Information</div>
    <div class="card-body">
        <div class="card-body row">
            <div class="form-group col-md">
                <label class="d-flex justify-content-center">
                    @Html.DisplayNameFor(model => model.Product.Category.Name)
                </label>
                <input class="form-control" disabled value="@Html.DisplayFor(model => model.Product.Category.Name)" />
            </div>

            <div class="form-group col-md">
                <label class="d-flex justify-content-center">
                    @Html.DisplayNameFor(model => model.Product.Name)
                </label>
                <input class="form-control" disabled value="@Html.DisplayFor(model => model.Product.Name)" />
            </div>
            <div class="form-group col-md">
                <label class="d-flex justify-content-center">
                    @Html.DisplayNameFor(model => model.Product.Brand)
                </label>
                <input class="form-control" disabled value="@Html.DisplayFor(model => model.Product.Brand)" />
            </div>
        </div>
        <div class="form-group col-md">
            <label class="d-flex justify-content-center">
                @Html.DisplayNameFor(model => model.Product.Description)
            </label>
            <input class="form-control" disabled value="@Html.DisplayFor(model => model.Product.Description)" />
        </div>
    </div>
</div>




<div class="card mt-3">
    <div class="card-header font-weight-bolder text-white d-flex justify-content-center"> Supplier Information</div>
    <div class="card-body">
        <div class="card-body row">

            <div class="form-group col-md">
                <label class="d-flex justify-content-center">@Html.DisplayNameFor(model => model.Supplier.Name)</label>
                <input class="form-control" disabled value="@Html.DisplayFor(model => model.Supplier.Name)" />
            </div>
            <div class="form-group col-md">
                <label class="d-flex justify-content-center">@Html.DisplayNameFor(model => model.Supplier.Telephone)</label>
                <input class="form-control" disabled value="@Html.DisplayFor(model => model.Supplier.Telephone)" />
            </div>
            <div class="form-group col-md">
                <label class="d-flex justify-content-center">@Html.DisplayNameFor(model => model.Supplier.AccountNumber)</label>
                <input class="form-control" disabled value="@Html.DisplayFor(model => model.Supplier.AccountNumber)" />
            </div>


        </div>
    </div>
</div>

<div class="d-flex justify-content-center mt-2">
    <form asp-action="Delete">
        <input type="hidden" asp-for="TransactionId" />
        <input type="submit" value="Delete" class="btn btn-danger mr-2 " style="font-size:20px" />|
    </form>
    <div class="ml-2 d-flex btn btn-secondary justify-content-center">
        <a asp-action="Index" style="font-size:20px; color:white;"> Back</a>
    </div>
</div>

RCL_Inventory/Views/Transactions/Details.cshtml
@model RCL_Inventory.Models.Transaction

@{
    ViewData["Title"] = "Details";
}
<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
<link rel="stylesheet" href="//cdn.datatables.net/1.11.5/css/jquery.dataTables.min.css" />
<link rel="stylesheet" href="~/css/sitee.css" />
<link rel="stylesheet" href="~/css/category.css" />
<link rel="stylesheet" href="~/css/product.css" />

<hr />
<h2 class="title">Transaction Details</h2>
<hr />

<div>
    <div class="card mt-3">
        <div class="card-header font-weight-bolder d-flex justify-content-center pr-5 bg-blue text-white"> Transaction Type</div>
        <div class="card-body d-flex justify-content-center pl-5">
            <h5 class="col-sm-2">
                @Html.DisplayFor(model => model.TransactionType.Name)
            </h5>
        </div>
    </div>
</div>


<div class="card mt-3">
    <div class="card-header font-weight-bolder text-white d-flex  bg-blue justify-content-center"> Transaction Information</div>
    <div class="card-body">
        <div class="card-body row">
            <div class="form-group col-md">
                <label>
                    @Html.DisplayNameFor(model => model.Date)
                </label>
                <input class="form-control" disabled value="@Html.DisplayFor(model => model.Date)" />
            </div>

            <div class="form-group col-md">
                <label>
                    @Html.DisplayNameFor(model => model.Quantity)
                </label>
                <input class="form-control" disabled value="@Html.DisplayFor(model => model.Quantity)" />
            </div>
        </div>
    </div>
</div>

<div class="card mt-3">
    <div class="card-header font-weight-bolder text-white d-flex  bg-blue justify-content-center"> Product Information</div>
    <div class="card-body">
        <div class="card-body row">
            <div class="form-group col-md">
                <label>
                    @Html.DisplayNameFor(model => model.Product.Category.Name)
                </label>
                <input class="form-control" disabled value="@Html.DisplayFor(model => model.Product.Category.Name)" />
            </div>

            <div class="form-group col-md">
                <label>
                    @Html.DisplayNameFor(model => model.Product.Name)
                </label>
                <input class="form-control" disabled value="@Html.DisplayFor(model => model.Product.Name)" />
            </div>
            <div class="form-group col-md">
                <label>
                    @Html.DisplayNameFor(model => model.Product.Brand)
                </label>
                <input class="form-control" disabled value="@Html.DisplayFor(model => model.Product.Brand)" />
            </div>
        </div>
        <div class="form-group col-md">
            <label>
                @Html.DisplayNameFor(model => model.Product.Description)
            </label>
            <input class="form-control" disabled value="@Html.DisplayFor(model => model.Product.Description)" />
        </div>

    </div>
</div>

<div class="card mt-3">
    <div class="card-header font-weight-bolder text-white d-flex  bg-blue justify-content-center"> Supplier Information</div>
    <div class="card-body">


        <div class="card-body row">
            <div class="col-md">

                <div class="form-group col-md">
                    <label>@Html.DisplayNameFor(model => model.Supplier.SupplierId)</label>
                    <input class="form-control" disabled value="@Html.DisplayFor(model => model.SupplierId)" />
                </div>
                <div class="form-group col-md">
                    <label>@Html.DisplayNameFor(model => model.Supplier.Telephone) </label>
                    <input class="form-control" disabled value="@Html.DisplayFor(model => model.Supplier.Telephone)" />
                </div>

            </div>

            <div class="col-md">
                <div class="form-group col-md">
                    <label>@Html.DisplayNameFor(model => model.Supplier.Name)</label>
                    <input class="form-control" disabled value="@Html.DisplayFor(model => model.Supplier.Name)" />
                </div>


                <div class="form-group col-md">
                    <label> @Html.DisplayNameFor(model => model.Supplier.AccountNumber) </label>
                    <input class="form-control" disabled value="@Html.DisplayFor(model => model.Supplier.AccountNumber)" />
                </div>
            </div>
        </div>
    </div>
</div>


<div class="d-flex justify-content-center mt-2">
    <div class="mr-2">
        <a asp-action="Edit" asp-route-id="@Model.TransactionId" input type="submit" class="btn btn-primary mr-2" style="font-size:20px">Edit</a>|
    </div>
    <div class="ml-2 d-flex btn btn-secondary justify-content-center">
        <a asp-action="Index" style="font-size:20px; color:white;"> Back</a>
    </div>
</div>