RCL_Inventory/Controllers/AboutUsController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Identity;
using RCL_Inventory.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.Extensions.Logging;


namespace RCL_Inventory.Controllers
{
    public class AboutUsController : Controller
    {
        private readonly ILogger<AboutUsController> _logger;


        public AboutUsController(ILogger<AboutUsController> logger)
        {
            _logger = logger;
        }


        // Method Get to show the About Us View.
        public IActionResult Index()
        {
            return View();
        }
    }
}

RCL_Inventory/Controllers/AddressesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using RCL_Inventory.Models;

namespace RCL_Inventory.Controllers
{
    [Authorize(Roles = "Admin")]
    public class AddressesController : Controller
    {
        private readonly InventoryContext _context;

        public AddressesController(InventoryContext context)
        {
            _context = context;
        }

        // Method Get to show Address Information.
        public async Task<IActionResult> Index()
        {
            return View(await _context.Addresses.ToListAsync());
        }


        // Method Get of Details Address.
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var address = await _context.Addresses
                .FirstOrDefaultAsync(m => m.AddressId == id);
            if (address == null)
            {
                return NotFound();
            }

            return View(address);
        }


        // Method Get of Create a new Address.
        public IActionResult Create()
        {
            return View();
        }

        // Method Post of Create a new Address.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("AddressId,Country,City,Province,PostalCode,Street")] Address address)
        {
            if (ModelState.IsValid)
            {
                _context.Add(address);
                await _context.SaveChangesAsync();
                TempData["success"] = "Information Added successfully.";
                return RedirectToAction(nameof(Index));
            }
            TempData["failed"] = "Failed. Please, select and fill all the fields.";
            return View(address);
        }

        // Method Get of Edit Address.
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var address = await _context.Addresses.FindAsync(id);
            if (address == null)
            {
                return NotFound();
            }
            return View(address);
        }

        // Method Post of Edit Address.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("AddressId,Country,City,Province,PostalCode,Street")] Address address)
        {
            if (id != address.AddressId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(address);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AddressExists(address.AddressId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                TempData["success"] = "Information edited successfully.";
                return RedirectToAction(nameof(Index));
            }
            TempData["failed"] = "Failed. Please, fill all the fields.";
            return View(address);
        }

        // Method Get of Delete Address.
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var address = await _context.Addresses
                .FirstOrDefaultAsync(m => m.AddressId == id);
            if (address == null)
            {
                return NotFound();
            }

            return View(address);
        }

        // Method Post of Delete Address.
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var address = await _context.Addresses.FindAsync(id);
            _context.Addresses.Remove(address);
            await _context.SaveChangesAsync();
            TempData["success"] = "Information deleted successfully.";
            return RedirectToAction(nameof(Index));
        }

        private bool AddressExists(int id)
        {
            return _context.Addresses.Any(e => e.AddressId == id);
        }
    }
}

RCL_Inventory/Controllers/ProductsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using RCL_Inventory.Models;
using RCL_Inventory.Models.ViewModels.ViewModelProduct;
using Microsoft.AspNetCore.Authorization;

namespace RCL_Inventory.Controllers
{
    [Authorize]
    public class ProductsController : Controller
    {
        private readonly InventoryContext _context;

        public ProductsController(InventoryContext context)
        {
            _context = context;
        }

        // Method Get of Products Information.
        public IActionResult Index()
        {
            var inventoryContext = _context.Products.Include(p => p.Category);
            return View(inventoryContext.ToList());
        }

        // Method Get of Products Details.
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var product = await _context.Products
                .Include(p => p.Category)
                .FirstOrDefaultAsync(m => m.ProductId == id);
            if (product == null)
            {
                return NotFound();
            }

            return View(product);
        }

        // Method Get of Create a new Product.
        public IActionResult Create()
        {
            var categories = _context.Categories.ToList();

             ProductViewModel ppvw = new ProductViewModel()
            {
                CategoriesList = categories
            };
            return View(ppvw);
        }

        // Method Post of Create a new Product.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ProductId,Name,Description,Brand,CategoryId")] Product product)
        {

            if (ModelState.IsValid)
            {
                _context.Add(product);
                await _context.SaveChangesAsync();
                TempData["success"] = "Information Added successfully.";
                return RedirectToAction(nameof(Index));
            }

            var categories = _context.Categories.ToList();

            ProductViewModel ppvw = new ProductViewModel()
            {
                CategoriesList = categories
            };

            TempData["failed"] = "Failed. Please, select and fill all the fields.";
            ViewData["CategoryId"] = new SelectList(_context.Categories, "CategoryId", "Name", product.CategoryId);
            return View(ppvw);
        }

        // Method Get of Edit a Product.
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var product = await _context.Products.FindAsync(id);

            int productId = product.ProductId;
            ProductViewModel pvm = new ProductViewModel()
            {
                CategoriesList = _context.Categories.ToList(),
                ProductId = productId
            };


            if (product == null)
            {
                return NotFound();
            }
            ViewData["CategoryId"] = new SelectList(_context.Categories, "CategoryId", "Name", product.CategoryId);

            return View(pvm);
        }

        // Method Post of Edit a Product.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ProductId,Name,Description,Brand,CategoryId")] Product product)
        {

            if (ModelState.IsValid)
            {

                Product productClass = new Product()
                {
                    ProductId = id,
                    CategoryId = product.CategoryId,
                    Name = product.Name,
                    Brand = product.Brand,
                    Description = product.Description
                };


                try
                {
                    _context.Update(productClass);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProductExists(product.ProductId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                TempData["success"] = "Information edited successfully.";
                return RedirectToAction(nameof(Index));
            }

            ProductViewModel pvm = new ProductViewModel()
            {
                CategoriesList = _context.Categories.ToList(),
                ProductId = id
            };
            TempData["failed"] = "Failed. Please, select and fill all the fields.";
            ViewData["CategoryId"] = new SelectList(_context.Categories, "CategoryId", "Name", product.CategoryId);
            return View(pvm);
        }

        // Method Get of Delete a Product.
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var product = await _context.Products
                .Include(p => p.Category)
                .FirstOrDefaultAsync(m => m.ProductId == id);
            if (product == null)
            {
                return NotFound();
            }

            return View(product);
        }

        // Method Post of Delete a Product.
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var product = await _context.Products.FindAsync(id);
            _context.Products.Remove(product);
            await _context.SaveChangesAsync();
            TempData["success"] = "Information deleted successfully.";
            return RedirectToAction(nameof(Index));
        }

        private bool ProductExists(int id)
        {
            return _context.Products.Any(e => e.ProductId == id);
        }
    }
}

RCL_Inventory/Controllers/UserController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using RCL_Inventory.Models;


namespace RCL_Inventory.Controllers
{
    [Authorize(Roles = "Admin")]
    public class UserController : Controller
    {
        private UserManager<User> userManager;
        private RoleManager<IdentityRole> roleManager;

        public UserController(UserManager<User> userMngr,
        RoleManager<IdentityRole> roleMngr)
        {
            userManager = userMngr;
            roleManager = roleMngr;
        }

        public async Task<IActionResult> Index()
        {
            List<User> users = new List<User>();
            foreach (User user in userManager.Users)
            {
                user.RoleNames = await userManager.GetRolesAsync(user);
                users.Add(user);
            }
            UserViewModel model = new UserViewModel
            {
                Users = users,
                Roles = roleManager.Roles
            };
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Delete(string id)
        {
            User user = await userManager.FindByIdAsync(id);
            if (user != null)
            {
                IdentityResult result = await userManager.DeleteAsync(user);
                if (!result.Succeeded)
                { // if failed
                    string errorMessage = "";
                    foreach (IdentityError error in result.Errors)
                    {
                        errorMessage += error.Description + " | ";
                    }
                    TempData["message"] = errorMessage;
                }
            }
            return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<IActionResult> AddToAdmin(string id)
        {
            IdentityRole adminRole =
                await roleManager.FindByNameAsync("Admin");
            if (adminRole == null)
            {
                TempData["message"] = "Admin role does not exist. "
                    + "Click 'Create Admin Role' button to create it.";
            }
            else
            {
                User user = await userManager.FindByIdAsync(id);
                await userManager.AddToRoleAsync(user, adminRole.Name);
            }
            return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<IActionResult> RemoveFromAdmin(string id)
        {
            User user = await userManager.FindByIdAsync(id);
            await userManager.RemoveFromRoleAsync(user, "Admin");
            return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<IActionResult> DeleteRole(string id)
        {
            IdentityRole role = await roleManager.FindByIdAsync(id);
            await roleManager.DeleteAsync(role);
            return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<IActionResult> CreateAdminRole()
        {
            await roleManager.CreateAsync(new IdentityRole("Admin"));
            return RedirectToAction("Index");
        }

        // the other action methods

    }
}

RCL_Inventory/Views/Shared/_AdminLayout.cshtml
@{
    Layout = "_Layout";
}

@section scripts {
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
}

<ul class="nav nav-tabs mt-2 mb-3">

    <li class="nav-item">
        <a class="nav-link" asp-action="Index" asp-controller="User" asp-area="Admin">Manage Users</a>
    </li>
</ul>

@RenderBody()

RCL_Inventory/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - RCL_Inventory</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="//cdn.datatables.net/1.11.5/css/jquery.dataTables.min.css" />
    <script src='https://kit.fontawesome.com/a076d05399.js' crossorigin='anonymous'></script>
    <link rel="stylesheet" href="~/css/sitee.css" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="//cdn.datatables.net/1.11.5/css/jquery.dataTables.min.css" />
    <link rel="stylesheet" href="~/css/sitee.css" />
    <link rel="stylesheet" href="~/css/product.css" />
    <link rel="stylesheet" href="~/css/category.css" />
</head>

<body>
    <header>
        <div id="main">
            <div class="container">
                <div style="margin-top:10px;margin-bottom:10px;text-align:center;">
                    <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                        <img src="~/images/logoRCLfinal.png" style="width:100px;margin-bottom:15px;position:center">
                    </a>
                    <h3 class="title">Inventory Management Solutions</h3>
                </div>
                <nav>
                    <div class="nav-fostrap text-center">
                        <ul>
                            <li><a asp-area="" asp-controller="Home" asp-action="Index">Dashboard</a></li>

                            <li>
                                <a asp-area="" asp-controller="Categories" asp-action="Index">Categories<span class="arrow-down"></span></a>

                                <ul class="dropdown">
                                    <li><a asp-area="" asp-controller="Categories" asp-action="Index">Categories</a></li>
                                    <li><a asp-area="" asp-controller="Categories" asp-action="Create">New Product Category</a></li>

                                </ul>
                            </li>

                            <li>
                                <a asp-area="" asp-controller="Products" asp-action="Index">Products<span class="arrow-down"></span></a>
                                <ul class="dropdown">
                                    <li><a asp-area="" asp-controller="Products" asp-action="Index">Products</a></li>
                                    <li><a asp-area="" asp-controller="Products" asp-action="Create">Create a new Product</a></li>
                                </ul>
                            </li>


                            <li><a asp-area="" asp-controller="Transactions" asp-action="Index">Transactions</a></li>




                            @if (signInManager.IsSignedIn(User) && User.IsInRole("Admin"))
                            {
                                <li>
                                    <a asp-area="" asp-controller="Addresses" asp-action="Index">Addresses<span class="arrow-down"></span></a>
                                    <ul class="dropdown">
                                        <li><a asp-area="" asp-controller="Addresses" asp-action="Index">Address</a></li>
                                        <li><a asp-area="" asp-controller="Addresses" asp-action="Create">Create new Address</a></li>
                                    </ul>
                                </li>

                            }


                            @if (signInManager.IsSignedIn(User) && User.IsInRole("Admin"))

                            {
                                <li>
                                    <a asp-area="" asp-controller="Suppliers" asp-action="Index">Suppliers<span class="arrow-down"></span></a>
                                    <ul class="dropdown">
                                        <li><a asp-area="" asp-controller="Suppliers" asp-action="Index">Suppliers</a></li>
                                        <li><a asp-area="" asp-controller="Suppliers" asp-action="Create">Create new Supplier</a></li>
                                    </ul>
                                </li>

                            }


                            @if (signInManager.IsSignedIn(User) && User.IsInRole("Admin"))
                            {
                                <li><a asp-area="" asp-controller="User" asp-action="Index">Users</a></li>
                            }


                            @inject SignInManager<User> signInManager
                            @if (signInManager.IsSignedIn(User))
                            {
                                // signed-in user - Log Out button and username
                                <li>
                                    <form method="post" asp-action="Logout" asp-controller="Account" asp-area="">
                                        <button type="submit" class="btn btn-outline-light"><i class="fa fa-unlock" aria-hidden="true"></i></button>
                                        @*<span class="text-light">Hello @User.Identity.Name!</span>*@
                                        <icon-icon><i class='fas fa-user-alt' style="font-size:larger"> @User.Identity.Name</i>
                                    </form>
                                </li>
                            }
                            else
                            {
                                // anonymous user - Register link and Log In button

                                <li><a asp-area="" asp-controller="ContactUs" asp-action="Index">Contact Us</a></li>
                                <li><a asp-area="" asp-controller="AboutUs" asp-action="Index">About</a></li>
                                <li class="nav-item">
                                    <a asp-area="" asp-controller="Account" asp-action="Login"><i class="fa fa-lock"> Log In</i></a>
                                    @*<a asp-action="Login" asp-controller="Account"
                                        asp-area="" class="btn btn-outline-light">Log In</a>*@
                                </li>
                            }

                            @*@if (signInManager.IsSignedIn(User) && User.IsInRole("Admin"))
                                {
                                    // get current action
                                    var action = ViewContext.RouteData.Values["action"]?.ToString();

                                    <li class="nav-item @Nav.Active("Register", action)">
                                        <a asp-action="Register" asp-controller="Account"
                                           asp-area="" class="nav-link">Register</a>
                                    </li>
                                }*@


                            @*@if (signInManager.IsSignedIn(User) && User.IsInRole("Admin"))
                                {
                                    <li class="nav-item">
                                        <a class="nav-link" asp-action="Index" asp-controller="User" asp-area="Admin"
                                           my-mark-area-active>
                                            <span class="fas fa-cog"></span>&nbsp;Admin
                                        </a>
                                    </li>
                                }*@

                        </ul>

                    </div>
                </nav>
            </div>

            <div class="nav-bg-fostrap">
                <div class="navbar-fostrap"> <span></span> <span></span> <span></span> </div>
                <a href="" class="title-mobile"></a>
            </div>
            <div class='content'>
            </div>
        </div>

    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            <div style="margin-top:auto;">
                &copy; 2022 - RCL Solutions
            </div>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.0/jquery.min.js"></script>
    <script src="//cdn.datatables.net/1.11.5/js/jquery.dataTables.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>